name: CI

on:
  pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Configure maven settings
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          repositories: '[{
            "id": "sadapay-nexus",
            "url": "http://ec2-3-249-244-209.eu-west-1.compute.amazonaws.com:8081/repository/maven-releases/",
            "releases": { "enabled": "true" },
            "snapshots": { "enabled": "false" }
             }]'
          servers: '[{
            "id": "sadapay-nexus",
            "username": "admin",
            "password": "${NEXUS_PASSWORD}"
            }]'

      - name: Maven clean install
        env:
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: mvn -ntp clean install

      - name: Run integration tests
        run: mvn -ntp -DfailIfNoTests=false failsafe:integration-test failsafe:verify -Pit

