name: Release

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Configure Maven settings
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          repositories: '[{
            "id": "sadapay-nexus",
            "url": "http://ec2-3-249-244-209.eu-west-1.compute.amazonaws.com:8081/repository/maven-releases/",
            "releases": { "enabled": "true" },
            "snapshots": { "enabled": "false" }
             }]'
          servers: '[{
            "id": "sadapay-nexus",
            "username": "admin",
            "password": "${NEXUS_PASSWORD}"
            }]'

      - name: Configure git
        run: |
          git config --global user.email "noreply@github.com"
          git config --global user.name "GitHub"

      - name: Prepare release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: mvn --batch-mode --no-transfer-progress release:prepare -Dusername=$GITHUB_ACTOR -Dpassword=$GITHUB_TOKEN

      - name: Perform release
        env:
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: mvn --batch-mode  --no-transfer-progress release:perform
