name: Sonar
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Configure maven settings
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          repositories: '[{
             "id": "sadapay-nexus",
             "url": "http://ec2-3-249-244-209.eu-west-1.compute.amazonaws.com:8081/repository/maven-releases/",
             "releases": { "enabled": "true" },
             "snapshots": { "enabled": "false" }
              }]'
          servers: '[{
             "id": "sadapay-nexus",
             "username": "admin",
             "password": "${NEXUS_PASSWORD}"
             }]'

      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_PROJECT_KEY: SadaPay_${{ github.event.repository.name }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: mvn -ntp clean verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.organization=sadapay -Dsonar.login=${{ secrets.SONAR_LOGIN_TOKEN }} -Dsonar.java.source=11
